"""
API Routes

All API route modules for the Adaptive Omni ML platform.
"""

from backend.app.api.routes import (
    auth,
    dashboard,
    modes,
    training,
    data_sources,
    data_pipeline,
    datasets,
    research,
    knowledge,
    knowledge_gaps,
    continual_learning,
    anti_forgetting,
    evaluation,
    benchmarks,
    experiments,
    models,
    model_registry,
    model_promotion,
    model_rollback,
    adapters,
    serving,
    local_model,
    providers,
    ai_router,
    conversations,
    memory,
    agents,
    monitoring,
    logs,
    system_settings,
    backups,
)

__all__ = [
    "auth",
    "dashboard",
    "modes",
    "training",
    "data_sources",
    "data_pipeline",
    "datasets",
    "research",
    "knowledge",
    "knowledge_gaps",
    "continual_learning",
    "anti_forgetting",
    "evaluation",
    "benchmarks",
    "experiments",
    "models",
    "model_registry",
    "model_promotion",
    "model_rollback",
    "adapters",
    "serving",
    "local_model",
    "providers",
    "ai_router",
    "conversations",
    "memory",
    "agents",
    "monitoring",
    "logs",
    "system_settings",
    "backups",
]
