"""
Training Monitor for Adaptive Qwen Omni.
Monitors and logs training metrics.
"""

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Union
import logging
import time
import json
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class MonitorConfig:
    """Configuration for training monitor."""
    log_dir: str = "./logs"
    log_interval: int = 10  # steps
    save_interval: int = 100  # steps
    use_tensorboard: bool = False
    use_mlflow: bool = True
    use_wandb: bool = False

    # Metrics to track
    track_loss: bool = True
    track_accuracy: bool = True
    track_learning_rate: bool = True
    track_gradient_norm: bool = True
    track_memory: bool = True

    # Alerting
    alert_on_nan: bool = True
    alert_on_exploding_gradients: bool = True
    gradient_threshold: float = 100.0


@dataclass
class TrainingMetrics:
    """Metrics collected during training."""
    step: int = 0
    epoch: int = 0
    loss: float = 0.0
    new_data_loss: float = 0.0
    replay_data_loss: float = 0.0
    distillation_loss: float = 0.0
    ewc_loss: float = 0.0
    accuracy: float = 0.0
    learning_rate: float = 0.0
    gradient_norm: float = 0.0
    memory_usage_gb: float = 0.0
    gpu_memory_usage_gb: float = 0.0
    time_per_step: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "step": self.step,
            "epoch": self.epoch,
            "loss": self.loss,
            "new_data_loss": self.new_data_loss,
            "replay_data_loss": self.replay_data_loss,
            "distillation_loss": self.distillation_loss,
            "ewc_loss": self.ewc_loss,
            "accuracy": self.accuracy,
            "learning_rate": self.learning_rate,
            "gradient_norm": self.gradient_norm,
            "memory_usage_gb": self.memory_usage_gb,
            "gpu_memory_usage_gb": self.gpu_memory_usage_gb,
            "time_per_step": self.time_per_step,
        }

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict())


@dataclass
class Alert:
    """Alert generated by the monitor."""
    level: str = "warning"  # info, warning, error
    message: str = ""
    step: int = 0
    epoch: int = 0
    timestamp: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "level": self.level,
            "message": self.message,
            "step": self.step,
            "epoch": self.epoch,
            "timestamp": self.timestamp,
        }


class TrainingMonitor:
    """
    Monitors training progress and metrics.

    Features:
    - Log metrics to file
    - Integrate with TensorBoard, MLflow, Weights & Biases
    - Detect anomalies (NaN, exploding gradients)
    - Generate alerts
    - Track best metrics
    """

    def __init__(self, config: Optional[MonitorConfig] = None):
        """
        Initialize training monitor.

        Args:
            config: Monitor configuration
        """
        self.config = config or MonitorConfig()

        # Setup logging directory
        self.log_dir = Path(self.config.log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Metrics storage
        self.metrics: List[TrainingMetrics] = []
        self.alerts: List[Alert] = []

        # Best metrics
        self.best_loss: float = float('inf')
        self.best_accuracy: float = 0.0

        # Timing
        self.start_time: float = time.time()
        self.last_log_time: float = time.time()
        self.last_step: int = 0

        # Setup external loggers
        self._setup_external_loggers()

    def _setup_external_loggers(self) -> None:
        """Setup external logging services."""
        if self.config.use_mlflow:
            try:
                import mlflow
                self.mlflow_available = True
            except ImportError:
                self.mlflow_available = False
                logger.warning("MLflow not available")
        else:
            self.mlflow_available = False

        if self.config.use_tensorboard:
            try:
                from torch.utils.tensorboard import SummaryWriter
                self.tensorboard_writer = SummaryWriter(log_dir=str(self.log_dir / "tensorboard"))
                self.tensorboard_available = True
            except ImportError:
                self.tensorboard_available = False
                logger.warning("TensorBoard not available")
        else:
            self.tensorboard_available = False

        if self.config.use_wandb:
            try:
                import wandb
                self.wandb_available = True
            except ImportError:
                self.wandb_available = False
                logger.warning("Weights & Biases not available")
        else:
            self.wandb_available = False

    def log(
        self,
        metrics: TrainingMetrics,
        step: int,
        epoch: int,
    ) -> None:
        """
        Log training metrics.

        Args:
            metrics: Metrics to log
            step: Training step
            epoch: Training epoch
        """
        # Update metrics
        metrics.step = step
        metrics.epoch = epoch

        # Calculate time per step
        current_time = time.time()
        if step > self.last_step:
            metrics.time_per_step = (current_time - self.last_log_time) / (step - self.last_step)
        self.last_step = step
        self.last_log_time = current_time

        # Store metrics
        self.metrics.append(metrics)

        # Check for anomalies
        self._check_anomalies(metrics, step, epoch)

        # Update best metrics
        if metrics.loss < self.best_loss:
            self.best_loss = metrics.loss
        if metrics.accuracy > self.best_accuracy:
            self.best_accuracy = metrics.accuracy

        # Log to file
        if step % self.config.log_interval == 0:
            self._log_to_file(metrics)

        # Log to external services
        if self.tensorboard_available:
            self._log_to_tensorboard(metrics, step)
        if self.mlflow_available:
            self._log_to_mlflow(metrics, step)
        if self.wandb_available:
            self._log_to_wandb(metrics, step)

    def _check_anomalies(
        self,
        metrics: TrainingMetrics,
        step: int,
        epoch: int,
    ) -> None:
        """Check for training anomalies."""
        import math

        # Check for NaN
        if self.config.alert_on_nan:
            if math.isnan(metrics.loss):
                self._add_alert(
                    level="error",
                    message=f"NaN loss detected at step {step}",
                    step=step,
                    epoch=epoch,
                )
            if math.isnan(metrics.accuracy):
                self._add_alert(
                    level="error",
                    message=f"NaN accuracy detected at step {step}",
                    step=step,
                    epoch=epoch,
                )

        # Check for exploding gradients
        if self.config.alert_on_exploding_gradients:
            if metrics.gradient_norm > self.config.gradient_threshold:
                self._add_alert(
                    level="warning",
                    message=f"High gradient norm: {metrics.gradient_norm:.2f} at step {step}",
                    step=step,
                    epoch=epoch,
                )

    def _add_alert(
        self,
        level: str,
        message: str,
        step: int,
        epoch: int,
    ) -> None:
        """Add an alert."""
        import time

        alert = Alert(
            level=level,
            message=message,
            step=step,
            epoch=epoch,
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
        )

        self.alerts.append(alert)

        # Log alert
        if level == "error":
            logger.error(f"ALERT: {message}")
        elif level == "warning":
            logger.warning(f"ALERT: {message}")
        else:
            logger.info(f"ALERT: {message}")

    def _log_to_file(self, metrics: TrainingMetrics) -> None:
        """Log metrics to file."""
        log_file = self.log_dir / "training_metrics.jsonl"

        with open(log_file, "a") as f:
            f.write(metrics.to_json() + "\n")

    def _log_to_tensorboard(self, metrics: TrainingMetrics, step: int) -> None:
        """Log metrics to TensorBoard."""
        if not self.tensorboard_available:
            return

        self.tensorboard_writer.add_scalar("Loss/train", metrics.loss, step)
        self.tensorboard_writer.add_scalar("Loss/new_data", metrics.new_data_loss, step)
        self.tensorboard_writer.add_scalar("Loss/replay", metrics.replay_data_loss, step)
        self.tensorboard_writer.add_scalar("Loss/distillation", metrics.distillation_loss, step)
        self.tensorboard_writer.add_scalar("Loss/ewc", metrics.ewc_loss, step)
        self.tensorboard_writer.add_scalar("Accuracy/train", metrics.accuracy, step)
        self.tensorboard_writer.add_scalar("Learning Rate", metrics.learning_rate, step)
        self.tensorboard_writer.add_scalar("Gradient Norm", metrics.gradient_norm, step)
        self.tensorboard_writer.add_scalar("Memory/CPU", metrics.memory_usage_gb, step)
        self.tensorboard_writer.add_scalar("Memory/GPU", metrics.gpu_memory_usage_gb, step)

    def _log_to_mlflow(self, metrics: TrainingMetrics, step: int) -> None:
        """Log metrics to MLflow."""
        if not self.mlflow_available:
            return

        import mlflow

        with mlflow.start_run(nested=True):
            mlflow.log_metric("loss", metrics.loss, step=step)
            mlflow.log_metric("new_data_loss", metrics.new_data_loss, step=step)
            mlflow.log_metric("replay_data_loss", metrics.replay_data_loss, step=step)
            mlflow.log_metric("accuracy", metrics.accuracy, step=step)
            mlflow.log_metric("learning_rate", metrics.learning_rate, step=step)
            mlflow.log_metric("gradient_norm", metrics.gradient_norm, step=step)

    def _log_to_wandb(self, metrics: TrainingMetrics, step: int) -> None:
        """Log metrics to Weights & Biases."""
        if not self.wandb_available:
            return

        import wandb

        wandb.log({
            "loss": metrics.loss,
            "new_data_loss": metrics.new_data_loss,
            "replay_data_loss": metrics.replay_data_loss,
            "accuracy": metrics.accuracy,
            "learning_rate": metrics.learning_rate,
            "gradient_norm": metrics.gradient_norm,
            "step": step,
        })

    def get_metrics(self) -> List[TrainingMetrics]:
        """Get all logged metrics."""
        return self.metrics

    def get_alerts(self) -> List[Alert]:
        """Get all alerts."""
        return self.alerts

    def get_summary(self) -> Dict[str, Any]:
        """Get training summary."""
        if not self.metrics:
            return {}

        total_steps = self.metrics[-1].step
        total_time = time.time() - self.start_time

        return {
            "total_steps": total_steps,
            "total_time_seconds": total_time,
            "steps_per_second": total_steps / total_time if total_time > 0 else 0,
            "best_loss": self.best_loss,
            "best_accuracy": self.best_accuracy,
            "current_loss": self.metrics[-1].loss,
            "current_accuracy": self.metrics[-1].accuracy,
            "num_alerts": len(self.alerts),
        }

    def save_summary(self, path: Optional[Union[str, Path]] = None) -> None:
        """Save training summary to file."""
        path = path or (self.log_dir / "summary.json")

        summary = self.get_summary()

        with open(path, "w") as f:
            json.dump(summary, f, indent=2)

        logger.info(f"Saved training summary to {path}")

    def close(self) -> None:
        """Close the monitor and cleanup."""
        if self.tensorboard_available:
            self.tensorboard_writer.close()

        logger.info("Training monitor closed")

    def __enter__(self) -> "TrainingMonitor":
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        """Context manager exit."""
        self.close()
